//! This is the build script that generates the config struct.
//! The layout and settings are defined in the config schema.

use std::fmt::Write;

const CONFIG_SCHEMA_PATH: &str = "config_schema.toml";
const CONFIG_PATH: &str = "config.toml";

const ANNOTATION_PREFIX: &str = "#:";

/// A parsed field from the annotated TOML config.
struct Field {
    key: String,
    rust_type: String,
    /// The raw TOML value string (e.g. `"hello"`, `42`, `true`).
    default_value: String,
}

/// A parsed [section] from the annotated TOML config.
struct Section {
    name: String,
    fields: Vec<Field>,
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

fn to_setting_type_name(section: &str, key: &str) -> String {
    let mut result = String::new();
    result.push_str(&to_pascal_case(section));
    result.push_str(&to_pascal_case(key));
    result.push_str("Setting");
    result
}

fn parse_config_schema(input: &str) -> Vec<Section> {
    let mut sections = Vec::new();
    let mut current_section: Option<Section> = None;
    let mut pending_type: Option<String> = None;

    for line in input.lines() {
        let trimmed = line.trim();

        // Type annotation: #: <type>
        if let Some(ty) = trimmed.strip_prefix(ANNOTATION_PREFIX) {
            pending_type = Some(ty.trim().to_string());
            continue;
        }

        // Section header: [name]
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            if let Some(section) = current_section.take() {
                sections.push(section);
            }
            let name = trimmed[1..trimmed.len() - 1].trim().to_string();
            current_section = Some(Section {
                name,
                fields: Vec::new(),
            });
            pending_type = None;
            continue;
        }

        // Skip comments and blank lines
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        // Skip continuation comment lines (lines that are just whitespace + #)
        if !trimmed.contains('=') {
            pending_type = None;
            continue;
        }

        // Key = value line
        if let Some(eq_pos) = trimmed.find('=') {
            let key = trimmed[..eq_pos].trim().to_string();

            // Extract value: everything after '=' up to an inline comment
            let after_eq = trimmed[eq_pos + 1..].trim();
            let value = extract_toml_value(after_eq);

            if let Some(rust_type) = pending_type.take() {
                if let Some(section) = current_section.as_mut() {
                    section.fields.push(Field {
                        key,
                        rust_type,
                        default_value: value,
                    });
                }
            } else {
                panic!(
                    "build.rs: config field '{}' is missing a #: type annotation",
                    key
                );
            }
        }
    }

    if let Some(section) = current_section {
        sections.push(section);
    }

    sections
}

fn extract_toml_value(s: &str) -> String {
    if let Some(after_quote) = s.strip_prefix('"') {
        // Find the closing quote
        if let Some(end_quote) = after_quote.find('"') {
            // Include both quotes
            s[..end_quote + 2].to_string()
        } else {
            panic!("build.rs: unterminated string in TOML value: {}", s);
        }
    } else {
        // Non-string: take until # comment or end of line
        let value = if let Some(hash_pos) = s.find('#') {
            s[..hash_pos].trim()
        } else {
            s.trim()
        };
        value.to_string()
    }
}

fn generate_code(sections: &[Section]) -> String {
    let mut out = String::new();

    // Header
    write!(
        out,
        r#"// This file was auto-generated by build.rs from {schema_path}

#[cfg(test)]
const CONFIG_SCHEMA_PATH: &str = "{schema_path}";
const CONFIG_PATH: &str = "{config_path}";
"#,
        schema_path = CONFIG_SCHEMA_PATH,
        config_path = CONFIG_PATH,
    )
    .unwrap();

    // Per-section: define_setting! invocations + XxxConfig struct
    for section in sections {
        let struct_name = format!("{}Config", to_pascal_case(&section.name));

        let settings = section
            .fields
            .iter()
            .map(|f| {
                format!(
                    "define_setting!({}, {}, {});",
                    to_setting_type_name(&section.name, &f.key),
                    f.rust_type,
                    f.default_value,
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        let struct_fields = section
            .fields
            .iter()
            .map(|f| {
                format!(
                    "    pub {}: {},",
                    f.key,
                    to_setting_type_name(&section.name, &f.key),
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        write!(
            out,
            r#"
{settings}

#[derive(Deserialize, Default)]
pub struct {struct_name} {{
{struct_fields}
}}
"#,
        )
        .unwrap();
    }

    // Config struct
    let config_fields = sections
        .iter()
        .map(|s| format!("    pub {}: {}Config,", s.name, to_pascal_case(&s.name)))
        .collect::<Vec<_>>()
        .join("\n");

    let layout_fields = sections
        .iter()
        .map(|s| {
            format!(
                "            {}: Option<{}Config>,",
                s.name,
                to_pascal_case(&s.name)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let unwrap_fields = sections
        .iter()
        .map(|s| {
            format!(
                "            {name}: parsed.{name}.unwrap_or_default(),",
                name = s.name
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    write!(
        out,
        r#"
#[derive(Default)]
pub struct Config {{
{config_fields}
}}
impl Config {{
    fn load(path: &str) -> Option<Self> {{
        #[derive(Deserialize)]
        struct ConfigLayout {{
{layout_fields}
        }}
        let file_read = std::fs::read_to_string(path);
        if let Err(e) = file_read {{
            if let std::io::ErrorKind::NotFound = e.kind() {{
                log(
                    Severity::Warning,
                    &format!("Config file {{}} missing, using default config", path),
                );
                return None;
            }} else {{
                panic_log(&format!("Can't open config file {{}}: {{}}", path, e));
            }}
        }}
        let file_contents = file_read.unwrap();
        let parsed: ConfigLayout = toml::from_str(&file_contents).unwrap_or_else(|e| {{
            panic_log(&format!("Malformed config file: {{}}", e));
        }});
        Some(Config {{
{unwrap_fields}
        }})
    }}
}}
"#,
    )
    .unwrap();

    out
}

fn strip_annotations(input: &str) -> String {
    let mut out = String::new();
    for line in input.lines() {
        if !line.trim_start().starts_with(ANNOTATION_PREFIX) {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn main() {
    println!("cargo:rerun-if-changed={}", CONFIG_SCHEMA_PATH);
    println!("cargo:rerun-if-changed={}", CONFIG_PATH);

    let input = std::fs::read_to_string(CONFIG_SCHEMA_PATH)
        .unwrap_or_else(|e| panic!("build.rs: can't read {}: {}", CONFIG_SCHEMA_PATH, e));

    let sections = parse_config_schema(&input);
    let code = generate_code(&sections);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = format!("{}/config_generated.rs", out_dir);
    std::fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("build.rs: can't write {}: {}", out_path, e));

    // Generate a clean config.toml (without type annotations) if one doesn't exist
    if !std::path::Path::new(CONFIG_PATH).exists() {
        let clean_toml = strip_annotations(&input);
        std::fs::write(CONFIG_PATH, clean_toml)
            .unwrap_or_else(|e| panic!("build.rs: can't write {}: {}", CONFIG_PATH, e));
        println!("cargo:warning=Generated default {}", CONFIG_PATH);
    }
}
