//! This is the build script that generates the config struct
//! and Luau type declarations for the scripting API.

use std::fmt::Write;

const CONFIG_SCHEMA_PATH: &str = "config_schema.toml";
const CONFIG_PATH: &str = "config.toml";

const LUAU_SCRIPTING_DIR: &str = "src/scripting";
const LUAU_DECL_PATH: &str = "scripts/globals.d.luau";

const ANNOTATION_PREFIX: &str = "#:";

fn main() {
    generate_config_structs();
    generate_luau_declarations();
}

// Config generation //

/// A parsed field from the annotated TOML config.
struct Field {
    key: String,
    rust_type: String,
    /// The raw TOML value string (e.g. `"hello"`, `42`, `true`).
    default_value: String,
}

/// A parsed [section] from the annotated TOML config.
struct Section {
    name: String,
    fields: Vec<Field>,
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

fn to_setting_type_name(section: &str, key: &str) -> String {
    let mut result = String::new();
    result.push_str(&to_pascal_case(section));
    result.push_str(&to_pascal_case(key));
    result.push_str("Setting");
    result
}

fn parse_config_schema(input: &str) -> Vec<Section> {
    let mut sections = Vec::new();
    let mut current_section: Option<Section> = None;
    let mut pending_type: Option<String> = None;

    for line in input.lines() {
        let trimmed = line.trim();

        // Type annotation: #: <type>
        if let Some(ty) = trimmed.strip_prefix(ANNOTATION_PREFIX) {
            pending_type = Some(ty.trim().to_string());
            continue;
        }

        // Section header: [name]
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            if let Some(section) = current_section.take() {
                sections.push(section);
            }
            let name = trimmed[1..trimmed.len() - 1].trim().to_string();
            current_section = Some(Section {
                name,
                fields: Vec::new(),
            });
            pending_type = None;
            continue;
        }

        // Skip comments and blank lines
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        // Skip continuation comment lines (lines that are just whitespace + #)
        if !trimmed.contains('=') {
            pending_type = None;
            continue;
        }

        // Key = value line
        if let Some(eq_pos) = trimmed.find('=') {
            let key = trimmed[..eq_pos].trim().to_string();

            // Extract value: everything after '=' up to an inline comment
            let after_eq = trimmed[eq_pos + 1..].trim();
            let value = extract_toml_value(after_eq);

            if let Some(rust_type) = pending_type.take() {
                if let Some(section) = current_section.as_mut() {
                    section.fields.push(Field {
                        key,
                        rust_type,
                        default_value: value,
                    });
                }
            } else {
                panic!(
                    "build.rs: config field '{}' is missing a #: type annotation",
                    key
                );
            }
        }
    }

    if let Some(section) = current_section {
        sections.push(section);
    }

    sections
}

fn extract_toml_value(s: &str) -> String {
    if let Some(after_quote) = s.strip_prefix('"') {
        // Find the closing quote
        if let Some(end_quote) = after_quote.find('"') {
            // Include both quotes
            s[..end_quote + 2].to_string()
        } else {
            panic!("build.rs: unterminated string in TOML value: {}", s);
        }
    } else {
        // Non-string: take until # comment or end of line
        let value = if let Some(hash_pos) = s.find('#') {
            s[..hash_pos].trim()
        } else {
            s.trim()
        };
        value.to_string()
    }
}

fn generate_code(sections: &[Section]) -> String {
    let mut out = String::new();

    // Header
    write!(
        out,
        r#"// This file was auto-generated by build.rs from {schema_path}

#[cfg(test)]
const CONFIG_SCHEMA_PATH: &str = "{schema_path}";
const CONFIG_PATH: &str = "{config_path}";
"#,
        schema_path = CONFIG_SCHEMA_PATH,
        config_path = CONFIG_PATH,
    )
    .unwrap();

    // Per-section: define_setting! invocations + XxxConfig struct
    for section in sections {
        let struct_name = format!("{}Config", to_pascal_case(&section.name));

        let settings = section
            .fields
            .iter()
            .map(|f| {
                format!(
                    "define_setting!({}, {}, {});",
                    to_setting_type_name(&section.name, &f.key),
                    f.rust_type,
                    f.default_value,
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        let struct_fields = section
            .fields
            .iter()
            .map(|f| {
                format!(
                    "    pub {}: {},",
                    f.key,
                    to_setting_type_name(&section.name, &f.key),
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        let merge_fields = section
            .fields
            .iter()
            .map(|f| {
                format!(
                    "        if other.{key}.is_set() {{ self.{key} = other.{key}; }}",
                    key = f.key,
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        write!(
            out,
            r#"
{settings}

#[derive(Deserialize, Default)]
pub struct {struct_name} {{
{struct_fields}
}}
impl {struct_name} {{
    fn merge(&mut self, other: Self) {{
{merge_fields}
    }}
}}
"#,
        )
        .unwrap();
    }

    // Config struct
    let config_fields = sections
        .iter()
        .map(|s| format!("    pub {}: {}Config,", s.name, to_pascal_case(&s.name)))
        .collect::<Vec<_>>()
        .join("\n");

    let layout_fields = sections
        .iter()
        .map(|s| {
            format!(
                "            {}: Option<{}Config>,",
                s.name,
                to_pascal_case(&s.name)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let unwrap_fields = sections
        .iter()
        .map(|s| {
            format!(
                "            {name}: parsed.{name}.unwrap_or_default(),",
                name = s.name
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let merge_sections = sections
        .iter()
        .map(|s| format!("        self.{name}.merge(other.{name});", name = s.name))
        .collect::<Vec<_>>()
        .join("\n");

    write!(
        out,
        r#"
#[derive(Default)]
pub struct Config {{
{config_fields}
}}
impl Config {{
    fn load(path: &str) -> FFResult<Self> {{
        let file_read = std::fs::read_to_string(path);
        if let Err(e) = file_read {{
            if let std::io::ErrorKind::NotFound = e.kind() {{
                log(
                    Severity::Warning,
                    &format!("Config file {{}} missing, using default config", path),
                );

                return Ok(Self::default());
            }} else {{
                return Err(FFError::build(
                    Severity::Fatal,
                    "Failed to read config file".to_string(),
                ).with_parent(e.into()));
            }}
        }}

        let file_contents = file_read.unwrap();
        let config = Config::from_str(&file_contents)?;
        Ok(config)
    }}

    fn from_str(toml_str: &str) -> FFResult<Self> {{
        #[derive(Deserialize)]
        struct ConfigLayout {{
{layout_fields}
        }}

        let parsed = toml::from_str::<ConfigLayout>(toml_str).map_err(|e| {{
            FFError::build(
                Severity::Fatal,
                format!("Failed to parse config overrides: {{}}", e),
            )
        }})?;

        Ok(Config {{
{unwrap_fields}
        }})
    }}

    fn merge(&mut self, other: Config) {{
{merge_sections}
    }}
}}
"#,
    )
    .unwrap();

    out
}

fn strip_annotations(input: &str) -> String {
    let mut out = String::new();
    for line in input.lines() {
        if !line.trim_start().starts_with(ANNOTATION_PREFIX) {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn generate_config_structs() {
    println!("cargo:rerun-if-changed={}", CONFIG_SCHEMA_PATH);
    println!("cargo:rerun-if-changed={}", CONFIG_PATH);

    let input = std::fs::read_to_string(CONFIG_SCHEMA_PATH)
        .unwrap_or_else(|e| panic!("build.rs: can't read {}: {}", CONFIG_SCHEMA_PATH, e));

    let sections = parse_config_schema(&input);
    let code = generate_code(&sections);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = format!("{}/config_generated.rs", out_dir);
    std::fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("build.rs: can't write {}: {}", out_path, e));

    // Generate a clean config.toml (without type annotations) if one doesn't exist
    if !std::path::Path::new(CONFIG_PATH).exists() {
        let clean_toml = strip_annotations(&input);
        std::fs::write(CONFIG_PATH, clean_toml)
            .unwrap_or_else(|e| panic!("build.rs: can't write {}: {}", CONFIG_PATH, e));
        println!("cargo:warning=Generated default {}", CONFIG_PATH);
    }
}

// Lua generation //

/// Rust type -> Luau type mapping for closure parameters.
fn rust_type_to_luau(ty: &str) -> String {
    if let Some(inner) = ty.strip_prefix("Option<").and_then(|s| s.strip_suffix('>')) {
        return format!("{}?", rust_type_to_luau(inner.trim()));
    }

    if let Some(inner) = ty.strip_prefix("Vec<").and_then(|s| s.strip_suffix('>')) {
        return format!("{{{}}}", rust_type_to_luau(inner.trim()));
    }

    match ty {
        "i32" | "u32" | "i64" | "u64" | "f32" | "f64" | "usize" | "isize" => "number",
        "bool" => "boolean",
        "String" | "&str" => "string",
        "EntityScriptContext" => "Entity",
        "NpcScriptContext" => "Npc",
        _ => ty,
    }
    .to_string()
}

/// Parse a closure parameter list like `(x, y, z): (i32, i32, i32)` or
/// `target: EntityScriptContext` or `()` and return Luau-formatted params (excluding `self`).
fn parse_closure_params(params_str: &str) -> Vec<String> {
    let params_str = params_str.trim();
    if params_str == "()" || params_str.is_empty() {
        return Vec::new();
    }

    // Tuple destructuring: (a, b, c): (T1, T2, T3)
    if let Some(colon_pos) = params_str.find("): (") {
        let names_part = &params_str[1..colon_pos]; // strip leading '('
        let types_start = colon_pos + 4; // skip "): ("
        let types_part = &params_str[types_start..params_str.len() - 1]; // strip trailing ')'
        let names: Vec<&str> = names_part.split(',').map(|s| s.trim()).collect();
        let types: Vec<&str> = types_part.split(',').map(|s| s.trim()).collect();
        return names
            .iter()
            .zip(types.iter())
            .map(|(n, t)| format!("{}: {}", n, rust_type_to_luau(t)))
            .collect();
    }

    // Single param: name: Type
    if let Some(colon_pos) = params_str.find(':') {
        let name = params_str[..colon_pos].trim();
        let ty = params_str[colon_pos + 1..].trim();
        return vec![format!("{}: {}", name, rust_type_to_luau(ty))];
    }

    Vec::new()
}

/// Collect all `.rs` files under a directory, sorted for deterministic output.
fn collect_rs_files(dir: &std::path::Path) -> Vec<std::path::PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(collect_rs_files(&path));
            } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                files.push(path);
            }
        }
    }

    files.sort();

    // mod.rs should always come first.
    files.sort_by_key(|p| {
        if p.file_name().and_then(|n| n.to_str()) == Some("mod.rs") {
            0
        } else {
            1
        }
    });

    files
}

/// Scan `src/scripting/**/*.rs` for `//@luau` annotations and `luau_method!`
/// invocations, then write `scripts/globals.d.luau`.
fn generate_luau_declarations() {
    use std::path::Path;

    let scripting_dir = Path::new(LUAU_SCRIPTING_DIR);
    println!("cargo:rerun-if-changed={}", LUAU_SCRIPTING_DIR);

    let source_files = collect_rs_files(scripting_dir);
    for path in &source_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut out =
        String::from("-- Auto-generated by build.rs from src/scripting/. Do not edit.\n\n");

    // Regexes for the luau macros:
    //   luau_type!("Name", "Definition");
    let type_re =
        regex::Regex::new(r#"(?s)luau_type!\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)"#).unwrap();
    //   luau_function!("name", "(params): ret");
    let func_re =
        regex::Regex::new(r#"(?s)luau_function!\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)"#).unwrap();
    //   luau_class!("ClassName", { ... });
    //   luau_class!("ClassName" extends "ParentClass", { ... });
    let class_re =
        regex::Regex::new(r#"luau_class!\("([^"]+)"(?:\s+extends\s+"([^"]+)")?\s*,"#).unwrap();
    //   luau_method!(ident, "name" -> "RetType", |_, this, params| { ... });
    let method_re = regex::Regex::new(
        r#"(?s)luau_method!\(\w+,\s*"([^"]+)"\s*->\s*"([^"]+)"\s*,\s*\|[^,]*,\s*\w+,\s*([^|]*)\|"#,
    )
    .unwrap();

    for path in &source_files {
        let content = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("build.rs: can't read {}: {}", path.display(), e));

        // Collect all fragments with their byte offset so we emit in source order
        let mut fragments: Vec<(usize, String)> = Vec::new();

        // luau_type!("Name", "Def") → export type Name = Def
        for caps in type_re.captures_iter(&content) {
            let offset = caps.get(0).unwrap().start();
            let name = &caps[1];
            let def = &caps[2];
            fragments.push((offset, format!("export type {} = {}\n", name, def)));
        }

        // luau_function!("name", "(params): ret") → declare function name(params): ret
        for caps in func_re.captures_iter(&content) {
            let offset = caps.get(0).unwrap().start();
            let name = &caps[1];
            let sig = &caps[2];
            fragments.push((offset, format!("declare function {}{}\n", name, sig)));
        }

        // luau_class!(Name, { → "declare class Name\n" at start,
        // find matching close → "end\n"
        for caps in class_re.captures_iter(&content) {
            let class_name = &caps[1];
            let extends = caps.get(2).map(|m| m.as_str());
            let match_start = caps.get(0).unwrap().start();
            let decl = match extends {
                Some(parent) => format!("declare class {} extends {}\n", class_name, parent),
                None => format!("declare class {}\n", class_name),
            };
            fragments.push((match_start, decl));

            // Find the opening '{' after the class name
            let after_match = caps.get(0).unwrap().end();
            if let Some(brace_offset) = content[after_match..].find('{') {
                let open_pos = after_match + brace_offset;
                // Count braces to find the matching close
                let mut depth = 0;
                let mut close_pos = open_pos;
                for (i, ch) in content[open_pos..].char_indices() {
                    match ch {
                        '{' => depth += 1,
                        '}' => {
                            depth -= 1;
                            if depth == 0 {
                                close_pos = open_pos + i;
                                break;
                            }
                        }
                        _ => {}
                    }
                }
                fragments.push((close_pos, "end\n".to_string()));
            }
        }

        // luau_method! → method declarations
        for caps in method_re.captures_iter(&content) {
            let offset = caps.get(0).unwrap().start();
            let name = &caps[1];
            let ret_type = caps[2].trim();
            let params_raw = caps[3].trim();

            let mut params = vec!["self".to_string()];
            params.extend(parse_closure_params(params_raw));
            let params_str = params.join(", ");

            fragments.push((
                offset,
                format!("    function {}({}): {}\n", name, params_str, ret_type),
            ));
        }

        fragments.sort_by_key(|(offset, _)| *offset);
        let mut prev_was_end = false;
        let mut prev_was_type = false;
        for (_, fragment) in &fragments {
            let is_class_start = fragment.starts_with("declare class ");
            let is_top_level = !fragment.starts_with("    ") && fragment.trim() != "end";
            let is_type = fragment.starts_with("export type ");
            let is_function = fragment.starts_with("declare function ");
            if (is_class_start && !out.ends_with("\n\n"))
                || (prev_was_end && is_top_level)
                || (prev_was_type && is_function)
            {
                out.push('\n');
            }
            out.push_str(fragment);
            prev_was_end = fragment.trim() == "end";
            prev_was_type = is_type;
        }
    }

    // Only rewrite if contents changed to avoid unnecessary LSP refreshes
    let current = std::fs::read_to_string(LUAU_DECL_PATH).unwrap_or_default();
    if current != out {
        std::fs::write(LUAU_DECL_PATH, &out)
            .unwrap_or_else(|e| panic!("build.rs: can't write {}: {}", LUAU_DECL_PATH, e));
    }
}
