name: Build and Check

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - src/**
      - sql/**
      - tabledata/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - src/**
      - sql/**
      - tabledata/**
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  read_msrv:
    name: Read MSRV
    uses: actions-rust-lang/msrv/.github/workflows/msrv.yml@main

  build_and_test_pg:
    name: Build and test (PostgreSQL)
    env:
      RUSTFLAGS: "-A dead_code"
    needs: read_msrv
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: rustyfusion
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d rustyfusion"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "stable, ${{ needs.read_msrv.outputs.msrv }}"
      - run: cargo build --verbose
      - run: cargo test -- --include-ignored
      - run: mv target/debug/* ./
      - uses: actions/upload-artifact@v6
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
        with:
          name: build-artifacts-debug-postgres
          path: |
            login
            shard
            hybrid
            config.toml
            docker-compose.yml
            LICENSE
            sql/*.sql
            scripts/
            tabledata/
          if-no-files-found: error

  build_and_test_sqlite:
    name: Build and test (sqlite)
    env:
      RUSTFLAGS: "-A dead_code"
    needs: read_msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "stable, ${{ needs.read_msrv.outputs.msrv }}"
      - run: cargo build --no-default-features --features sqlite --verbose
      - run: cargo test --no-default-features --features sqlite
      - run: mv target/debug/* ./
      - uses: actions/upload-artifact@v6
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
        with:
          name: build-artifacts-debug-sqlite
          path: |
            login
            shard
            hybrid
            config.toml
            LICENSE
            sql/
            scripts/
            tabledata/
          if-no-files-found: error

  formatting:
    name: Check formatting
    needs: read_msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "stable, ${{ needs.read_msrv.outputs.msrv }}"
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
