name: Build and Check

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - src/**
      - tabledata/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/rust.yml
      - src/**
      - tabledata/**
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  read_msrv:
    name: Read MSRV
    uses: actions-rust-lang/msrv/.github/workflows/msrv.yml@main

  build_and_test:
    name: Build and test
    env:
      RUSTFLAGS: "-A dead_code"
    needs: read_msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "stable, ${{ needs.read_msrv.outputs.msrv }}"
      - run: cargo build --verbose
      - run: cargo test
      - uses: actions/upload-artifact@v6
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
        with:
          name: build-artifacts-debug
          path: |
            target/debug/login
            target/debug/shard
          if-no-files-found: error

  # Check formatting with rustfmt
  formatting:
    name: Check formatting
    needs: read_msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "stable, ${{ needs.read_msrv.outputs.msrv }}"
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
